name: Confirm

on: [pull_request, push]

jobs:
  confirm:
    runs-on: ubuntu-latest
    env: 
      BASE_BRANCH: ${{ github.base_ref }}
      HEAD_BRANCH: ${{ github.head_ref }}

    steps:
      - uses: actions/checkout@v2

      - run: |
          echo github.base_ref is: ${BASE_BRANCH}

      - run: |
          echo github.head_ref	is: ${HEAD_BRANCH}
