# name: Ship js trigger
# on: pull_request

# jobs:
#   build:
#     name: Release
#     runs-on: ubuntu-latest
#     if: 
#     env: 
#       RELEASE_PULL_REQUEST_BRANCH: releases # add

#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: develop
#       - uses: actions/setup-node@v1
#         with:
#           registry-url: "https://registry.npmjs.org"
#       - run: |
#           if [ -f "yarn.lock" ]; then
#             yarn install
#           else
#             npm install
#           fi
#       - run: npx shipjs trigger
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
#           # SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
